### ISSUE TITLE
Hovering over operators causes view to jump around in infinite loop

### ISSUE THREAD

**Issue by kevcunnane** [phil-scott-78/azure-data-studio-queryplan-show#1]
Firstly, I love the direction this extension is going. One issue I've run into is on-hover changes the size of various components, and because this moves the box you're hovering away from the mouse it bounces back and forth (see gif below). This happens in all 3 tabs. Would be good to fix by finding a way to avoid resizing the outer boxes or something similar. 

![in](https://user-images.githubusercontent.com/10819925/53036956-d0a29780-342d-11e9-9c72-c134c7314cee.gif)

**Comment by phil-scott-78** [comment]
hmmm, interesting. obviously doesn't happen on my machine because that's pretty aggressive. I'll get on it and try and reproduce. Any chance you could paste your settings?

**Comment by kevcunnane** [comment]
Here's my settings. This is on macOS, my laptop monitor, ~1,047 width by 700 height.

![image](https://user-images.githubusercontent.com/10819925/53038187-f8dfc580-3430-11e9-8f73-44b16c33928e.png)


Azure Data Studio version: azuredatastudio 1.5.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Users/kevcunnane/projects/azuredatastudio/.build/electron/Azure Data Studio.app/Contents/MacOS/Electron . --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
server-report|Mic|0.1.4
sql-vnext|Mic|0.10.2
PowerShell|ms-|1.11.0
queryplan-show|phi|0.0.1


</details>

**Comment by kevcunnane** [comment]
Fixed it in latest, thanks!

**Comment by phil-scott-78** [comment]
@kevcunnane I think I might have actually finally found the right combination of query plan and browser size to reproduce. Looks like it came down to when the selected operator had a longer set of details than the selected one (or vice versa). On hover of the item the size of the operator display was changing and vue was getting cute trying to remember the scroll position. This was shifting things around causing a mouseout and returning to the previous size. Which caused the size of the operator to change again which caused vue to get cute trying to remember the scroll position and another adjustment leading to another mouseout. 

I have a small little workaround of changing the min-size of the display to a bit larger than the view window to hopefully minimize the opportunity for this to happen that I'll publish in the next release.
