### ISSUE TITLE
Feature request: indicator of overall plan size when zoomed in

### ISSUE THREAD

**Issue by kevcunnane** [phil-scott-78/azure-data-studio-queryplan-show#2]
It'd be really nice to see where we are in the view when zoomed in, with a zoom % and ideally some scrollbars so that we can use keyboard buttons / the left and right scroll function on a mouse to move instead of clicking and dragging.

**Comment by phil-scott-78** [comment]
Hey Kevin, just published a new version that throws out the previous version's handling of scrolling and zooming to use simple scrollbars and buttons for zooming. Should make it a bit more intuitive...I hope 

https://github.com/phil-scott-78/azure-data-studio-queryplan-show/releases/tag/0.0.2

**Comment by kevcunnane** [comment]
Thanks for fixing!
