### ISSUE TITLE
Azure Data Studio: Install from vsix

### ISSUE THREAD

**Issue by SQLDTAIT** [phil-scott-78/azure-data-studio-queryplan-show#5]
Receiving an error when trying to install; not compatible with Azure Data Studio 1.5.1 (latest release), this is on releases 0.02 -> 0.04.

**Comment by phil-scott-78** [comment]
thanks for the heads up. pushed up version [0.0.5](https://github.com/phil-scott-78/azure-data-studio-queryplan-show/releases/tag/v0.0.5) that supports the latest version

**Comment by SQLDTAIT** [comment]
Awesome!
